apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy1-service
  template:
    metadata:
      labels:
        app: deploy1-service
    spec:
      containers:
        - name: deploy1-img
          image: docker.io/zolaemma/class:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: deploy1-service
spec:
  selector:
    app: app-deploy1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
